include_directories(${PROJECT_BINARY_DIR}/generated)

file(MAKE_DIRECTORY ${PROJECT_BINARY_DIR}/generated)

# generate AO evaluation code
add_custom_command(
    OUTPUT
        ${PROJECT_BINARY_DIR}/generated/autogenerated.h
        ${PROJECT_BINARY_DIR}/generated/parameters.h
        ${PROJECT_BINARY_DIR}/generated/offsets.h
    COMMAND
        ${PYTHON_EXECUTABLE} ${PROJECT_SOURCE_DIR}/src/generate.py
                             ${PROJECT_BINARY_DIR}/generated
                             ${MAX_L_VALUE}
                             ${AO_CHUNK_LENGTH}
                             ${AO_BLOCK_LENGTH}
                             ${MAX_GEO_DIFF_ORDER}
    WORKING_DIRECTORY
        ${PROJECT_SOURCE_DIR}/src
    DEPENDS
        src/generate.py
        src/cs_trans.py
        ${PROJECT_SOURCE_DIR}/cmake/custom/parameters.cmake
    )

add_custom_target(
    generate
    ALL
    DEPENDS
        ${PROJECT_BINARY_DIR}/generated/parameters.h
    )
